language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov=pydune/
after_success:
  - coveralls